# -*- coding: utf-8 -*-
from decimal import *

# subscription type
Subscription = {
	'TRIAL': 5,
	'TIER_5': 5,
	'TIER_15': 20,
	'TIER_30': 50,
}

Tx = {
	'STATUS_PENDING': -1,
	'STATUS_DONE': 0
}

# handshake
Handshake = {
	'STATUS_SHAKER_ROLLBACK': -9,
	'STATUS_MAKER_UNINIT_PENDING': -8,
	'STATUS_COLLECT_PENDING': -7,
	'STATUS_REFUND_PENDING': -6,
	'STATUS_DISPUTE_PENDING': -5,
	'STATUS_BLOCKCHAIN_PENDING': -4,
	'STATUS_NEW': -3,
	'STATUS_MAKER_FAILED_INIT': -2,

	'STATUS_PENDING': -1,
	'STATUS_INITED': 0,
	'STATUS_MAKER_UNINITED': 1,
	'STATUS_SHAKER_SHAKED': 2,
	'STATUS_REFUNDED': 3,
	'STATUS_DISPUTED': 4,
	'STATUS_RESOLVED': 5,
	'STATUS_DONE': 6,

	'INDUSTRIES_NONE': 0,
	'INDUSTRIES_UPLOAD_DOCUMENT': 13,
	'INDUSTRIES_BETTING': 3
}


BLOCKCHAIN_NETWORK = {
	'MAIN': 1,
	'ROPSTEN': 2,
	'KOVAN': 3,
	'RINKEBY': 4,
	'LOCAL': 5
}

# Handshake state
HANDSHAKE_STATE = {
	'INIT': 0,
	'INTIATED': 1,
	'UNINIT': 2,
	'UNINITED': 3,
	'SHAKE': 4,
	'SHAKED': 5,
	'COLLECT': 6,
	'REFUND': 7,
	'DONE': 8
}

CRYPTOSIGN_OFFCHAIN_PREFIX = 'cryptosign_'
CRYPTOSIGN_MINIMUM_MONEY = Decimal('0.0005')

# COMMUNITY_TYPE
COMMUNITY_TYPE = {
	'PUBLIC': 0,
	'PRIVATE': 1
}

STATE_TYPE = {
	'NEW': 0,
	'PUBLISH': 1
}

RESULT_TYPE = {
	'PENDING': -1,
	'DRAW': 0,
	'SUPPORT_WIN': 1,
	'AGAINST_WIN': 2
}

SIDE_TYPE = {
	'DRAW': 0,
	'SUPPORT': 1,
	'AGAINST': 2
}