"""empty message

Revision ID: 0bb0b2cc0537
Revises: ee50c9d11bb9
Create Date: 2018-07-09 13:49:45.797471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0bb0b2cc0537'
down_revision = 'ee50c9d11bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onchain_task', sa.Column('contract_method', sa.String(length=255), nullable=True))
    op.drop_column('onchain_task', 'method_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onchain_task', sa.Column('method_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('onchain_task', 'contract_method')
    # ### end Alembic commands ###
