"""empty message

Revision ID: 140378bd9be7
Revises: 3e8b6518c8d1
Create Date: 2018-12-27 16:47:24.887112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '140378bd9be7'
down_revision = '3e8b6518c8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.add_column('tx', sa.Column('onchain_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tx', 'onchain_task', ['onchain_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tx', type_='foreignkey')
    op.drop_column('tx', 'onchain_task_id')
    op.create_table('comment',
    sa.Column('date_created', mysql.TIMESTAMP(), nullable=True),
    sa.Column('date_modified', mysql.TIMESTAMP(), nullable=True),
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('object_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
