"""empty message

Revision ID: 1ce7915a089e
Revises: ee50c9d11bb9
Create Date: 2018-07-09 12:13:21.621781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ce7915a089e'
down_revision = 'ee50c9d11bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('approved', sa.Integer(), server_default='1', nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('history')
    op.add_column(u'match', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column(u'match', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match', 'source', ['source_id'], ['id'])
    op.create_foreign_key(None, 'match', 'category', ['category_id'], ['id'])
    op.drop_column(u'match', 'source')
    op.add_column(u'onchain_task', sa.Column('contract_method', sa.String(length=255), nullable=True))
    op.drop_column(u'onchain_task', 'method_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'onchain_task', sa.Column('method_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column(u'onchain_task', 'contract_method')
    op.add_column(u'match', sa.Column('source', mysql.VARCHAR(length=256), nullable=True))
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column(u'match', 'source_id')
    op.drop_column(u'match', 'category_id')
    op.create_table('history',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('shaker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('handshake_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('maker_amount', mysql.FLOAT(), nullable=True),
    sa.Column('maker_odds', mysql.FLOAT(), nullable=True),
    sa.Column('shaker_amount', mysql.FLOAT(), nullable=True),
    sa.Column('shaker_odds', mysql.FLOAT(), nullable=True),
    sa.Column('modified_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], [u'user.id'], name=u'history_ibfk_1'),
    sa.ForeignKeyConstraint(['modified_user_id'], [u'user.id'], name=u'history_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('source')
    op.drop_table('category')
    # ### end Alembic commands ###
