"""empty message

Revision ID: 2ccb40667695
Revises: eb5737c16520
Create Date: 2018-06-12 12:30:33.612033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ccb40667695'
down_revision = 'eb5737c16520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handshake', 'win_value')
    op.drop_column('shaker', 'win_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaker', sa.Column('win_value', mysql.DECIMAL(precision=20, scale=18), nullable=True))
    op.add_column('handshake', sa.Column('win_value', mysql.DECIMAL(precision=20, scale=18), nullable=True))
    # ### end Alembic commands ###
