"""empty message

Revision ID: 3226fa765213
Revises: 72bbadc765fc
Create Date: 2018-06-11 12:04:10.031553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3226fa765213'
down_revision = '72bbadc765fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('source', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'source')
    # ### end Alembic commands ###
