"""empty message

Revision ID: 3e8b6518c8d1
Revises: c8ff9b97b90c
Create Date: 2018-12-11 10:24:38.584927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8b6518c8d1'
down_revision = 'c8ff9b97b90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome', sa.Column('approve_by', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome', 'approve_by')
    # ### end Alembic commands ###
