"""empty message

Revision ID: 412e35624de9
Revises: 8517d051a10b
Create Date: 2018-09-13 11:01:39.499416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412e35624de9'
down_revision = '8517d051a10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_subscribe', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_subscribe')
    # ### end Alembic commands ###
