"""empty message

Revision ID: 415e4188099d
Revises: 8def14a4268a
Create Date: 2018-09-11 17:59:40.583478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '415e4188099d'
down_revision = '8def14a4268a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'handshake_ibfk_5', 'handshake', type_='foreignkey')
    op.drop_column('handshake', 'view_count')
    op.drop_column('handshake', 'token_id')
    op.add_column('outcome', sa.Column('token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'outcome', 'token', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outcome', type_='foreignkey')
    op.drop_column('outcome', 'token_id')
    op.add_column('handshake', sa.Column('token_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('handshake', sa.Column('view_count', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True))
    op.create_foreign_key(u'handshake_ibfk_5', 'handshake', 'token', ['token_id'], ['id'])
    # ### end Alembic commands ###
