"""empty message

Revision ID: 4164abdb6a7d
Revises: d688e7d7307a
Create Date: 2018-10-29 15:47:38.809624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4164abdb6a7d'
down_revision = 'd688e7d7307a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'image_url')
    # ### end Alembic commands ###
