"""empty message

Revision ID: 43ff75f37363
Revises: 2f22cc33e21c
Create Date: 2018-06-07 16:44:10.247601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ff75f37363'
down_revision = 'c589730163c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('market_fee', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'market_fee')
    # ### end Alembic commands ###
