"""empty message

Revision ID: 46eab8e53d1c
Revises: a75b97ba0b30
Create Date: 2018-08-09 14:19:22.892673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46eab8e53d1c'
down_revision = 'a75b97ba0b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('contract_address', sa.String(length=255), nullable=True))
    op.add_column('task', sa.Column('contract_json', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'contract_json')
    op.drop_column('task', 'contract_address')
    # ### end Alembic commands ###
