"""empty message

Revision ID: 4bbb47e7f319
Revises: 99a3ec004cbb
Create Date: 2018-06-15 11:12:50.149004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbb47e7f319'
down_revision = '99a3ec004cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaker', sa.Column('chain_id', sa.Integer(), server_default='4', nullable=True))
    op.add_column('shaker', sa.Column('from_address', sa.String(length=255), nullable=True))
    op.add_column('tx', sa.Column('offchain', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tx', 'offchain')
    op.drop_column('shaker', 'from_address')
    op.drop_column('shaker', 'chain_id')
    # ### end Alembic commands ###
