"""empty message

Revision ID: 564abd7bdc60
Revises: 62696912de3e
Create Date: 2018-10-22 06:33:26.785962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '564abd7bdc60'
down_revision = '62696912de3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redeem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'match', 'approved')
    op.add_column(u'outcome', sa.Column('approved', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'outcome', 'approved')
    op.add_column(u'match', sa.Column('approved', mysql.INTEGER(display_width=11), server_default=sa.text(u"'1'"), autoincrement=False, nullable=True))
    op.drop_table('redeem')
    # ### end Alembic commands ###
