"""empty message

Revision ID: 5b1c6d82dde8
Revises: 0e45ab7da996
Create Date: 2018-10-15 23:19:27.685024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1c6d82dde8'
down_revision = '0e45ab7da996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('creator_wallet_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'creator_wallet_address')
    # ### end Alembic commands ###
