"""empty message

Revision ID: 6367dd76d342
Revises: fb1479b1dd49
Create Date: 2018-05-31 15:40:57.065361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6367dd76d342'
down_revision = 'fb1479b1dd49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome', sa.Column('tx', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome', 'tx')
    # ### end Alembic commands ###
