"""empty message

Revision ID: 64a4ef331e98
Revises: a040ac5c86e6
Create Date: 2018-06-19 10:52:32.447034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a4ef331e98'
down_revision = 'a040ac5c86e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaker', sa.Column('free_bet', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaker', 'free_bet')
    # ### end Alembic commands ###
