"""empty message

Revision ID: 667121278279
Revises: 64a4ef331e98
Create Date: 2018-06-20 16:27:39.953322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '667121278279'
down_revision = '64a4ef331e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonce')
    op.add_column('match', sa.Column('disputeTime', sa.BigInteger(), nullable=True))
    op.add_column('match', sa.Column('reportTime', sa.BigInteger(), nullable=True))
    op.drop_index('username', table_name='user')
    op.drop_index('uuid', table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'status')
    op.drop_column('user', 'uuid')
    op.drop_column('user', 'card_id')
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'ref_id')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'reward_wallet_addresses')
    op.drop_column('user', 'card_verified')
    op.drop_column('user', 'metadata')
    op.drop_column('user', 'email')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('metadata', mysql.VARCHAR(length=5000), nullable=True))
    op.add_column('user', sa.Column('card_verified', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('reward_wallet_addresses', mysql.VARCHAR(length=1000), nullable=True))
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('ref_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('card_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('uuid', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('user', sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text(u"'1'"), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('uuid', 'user', ['uuid'], unique=True)
    op.create_index('username', 'user', ['username'], unique=True)
    op.drop_column('match', 'reportTime')
    op.drop_column('match', 'disputeTime')
    op.create_table('nonce',
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('network_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nonce', mysql.INTEGER(display_width=11), server_default=sa.text(u"'1'"), autoincrement=False, nullable=True),
    sa.Column('timestmap', mysql.BIGINT(display_width=20), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('address', 'network_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
