"""empty message

Revision ID: 694a1a355139
Revises: 4164abdb6a7d
Create Date: 2018-11-02 16:26:39.726990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694a1a355139'
down_revision = '4164abdb6a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('event_name', sa.String(length=512), nullable=True))
    op.add_column('match', sa.Column('outcome_name', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'outcome_name')
    op.drop_column('match', 'event_name')
    # ### end Alembic commands ###
