"""empty message

Revision ID: 715e4ace7caf
Revises: e48cc83f7171
Create Date: 2018-08-15 09:25:49.482233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715e4ace7caf'
down_revision = 'e48cc83f7171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('contract_name', sa.String(length=255), nullable=True),
    sa.Column('contract_address', sa.String(length=255), nullable=True),
    sa.Column('json_name', sa.String(length=50), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'outcome', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'outcome', 'contract', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outcome', type_='foreignkey')
    op.drop_column(u'outcome', 'contract_id')
    op.drop_table('contract')
    # ### end Alembic commands ###
