"""empty message

Revision ID: 723f0bfda2d6
Revises: c8c6206af25d
Create Date: 2018-11-27 08:07:27.659483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723f0bfda2d6'
down_revision = 'c8c6206af25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('played_bet', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'played_bet')
    # ### end Alembic commands ###
