"""empty message

Revision ID: 72bbadc765fc
Revises: 43ff75f37363
Create Date: 2018-06-08 10:00:03.974310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bbadc765fc'
down_revision = '43ff75f37363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('payload', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'payload')
    # ### end Alembic commands ###
