"""empty message

Revision ID: 75ba52dbb778
Revises: 48bbca20c655
Create Date: 2018-06-30 10:52:36.795135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75ba52dbb778'
down_revision = '48bbca20c655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.add_column('setting', sa.Column('value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'value')
    op.create_table('event',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('event_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('value', mysql.TEXT(), nullable=True),
    sa.Column('block', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('log_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('modified_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], [u'user.id'], name=u'event_ibfk_1'),
    sa.ForeignKeyConstraint(['modified_user_id'], [u'user.id'], name=u'event_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
