"""empty message

Revision ID: 8517d051a10b
Revises: 415e4188099d
Create Date: 2018-09-12 09:21:40.548003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8517d051a10b'
down_revision = '415e4188099d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('approved', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'approved')
    # ### end Alembic commands ###
