"""empty message

Revision ID: 88d195683a69
Revises: 64a4ef331e98
Create Date: 2018-06-20 16:58:59.234888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d195683a69'
down_revision = '64a4ef331e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('disputeTime', sa.BigInteger(), nullable=True))
    op.add_column('match', sa.Column('reportTime', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'reportTime')
    op.drop_column('match', 'disputeTime')
    # ### end Alembic commands ###
