"""empty message

Revision ID: 961543dc2eb2
Revises: ccfccd7f5f71
Create Date: 2018-07-30 16:51:50.882025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961543dc2eb2'
down_revision = 'ccfccd7f5f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('index', sa.Integer(), server_default='1', nullable=True))
    op.add_column('outcome', sa.Column('index', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome', 'index')
    op.drop_column('match', 'index')
    # ### end Alembic commands ###
