"""empty message

Revision ID: 995ec7f25428
Revises: bd3fe8f32bbd
Create Date: 2018-07-17 18:33:59.353892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '995ec7f25428'
down_revision = 'bd3fe8f32bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome', sa.Column('total_dispute_amount', sa.Numeric(precision=20, scale=18), nullable=True))
    op.drop_column('outcome', 'total_amount_dispute')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome', sa.Column('total_amount_dispute', mysql.DECIMAL(precision=20, scale=18), nullable=True))
    op.drop_column('outcome', 'total_dispute_amount')
    # ### end Alembic commands ###
