"""empty message

Revision ID: 9c64a5f11f50
Revises: a74cb38a6d32
Create Date: 2019-02-19 16:24:56.309879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c64a5f11f50'
down_revision = 'a74cb38a6d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_token', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_token', 'contract', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_token', type_='foreignkey')
    op.drop_column('user_token', 'contract_id')
    # ### end Alembic commands ###
