"""empty message

Revision ID: a040ac5c86e6
Revises: 4bbb47e7f319
Create Date: 2018-06-19 10:49:30.350160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a040ac5c86e6'
down_revision = '4bbb47e7f319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handshake', sa.Column('free_bet', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handshake', 'free_bet')
    # ### end Alembic commands ###
