"""empty message

Revision ID: a565a5b3b2dd
Revises: 
Create Date: 2018-06-04 11:17:40.586231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a565a5b3b2dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('event_name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('block', sa.BigInteger(), nullable=True),
    sa.Column('log_index', sa.Integer(), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('shaker_id', sa.Integer(), nullable=True),
    sa.Column('handshake_id', sa.Integer(), nullable=True),
    sa.Column('maker_amount', sa.Float(), nullable=True),
    sa.Column('maker_odds', sa.Float(), nullable=True),
    sa.Column('shaker_amount', sa.Float(), nullable=True),
    sa.Column('shaker_odds', sa.Float(), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('homeTeamName', sa.String(length=255), nullable=True),
    sa.Column('homeTeamCode', sa.String(length=10), nullable=True),
    sa.Column('homeTeamFlag', sa.String(length=512), nullable=True),
    sa.Column('awayTeamName', sa.String(length=255), nullable=True),
    sa.Column('awayTeamCode', sa.String(length=10), nullable=True),
    sa.Column('awayTeamFlag', sa.String(length=512), nullable=True),
    sa.Column('homeScore', sa.Integer(), nullable=True),
    sa.Column('awayScore', sa.Integer(), nullable=True),
    sa.Column('date', sa.BigInteger(), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('hid', sa.BigInteger(), nullable=True),
    sa.Column('result', sa.Integer(), server_default='-1', nullable=True),
    sa.Column('tx', sa.String(length=255), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handshake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('hs_type', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('chain_id', sa.Integer(), server_default='4', nullable=True),
    sa.Column('state', sa.Integer(), server_default='1', nullable=True),
    sa.Column('is_private', sa.Integer(), server_default='0', nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), server_default='-1', nullable=True),
    sa.Column('bk_status', sa.Integer(), server_default='-1', nullable=True),
    sa.Column('shake_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('odds', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=18), nullable=True),
    sa.Column('remaining_amount', sa.Numeric(precision=20, scale=18), nullable=True),
    sa.Column('win_value', sa.Numeric(precision=20, scale=18), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('side', sa.Integer(), server_default='1', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shaker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('shaker_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=18), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('odds', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('win_value', sa.Numeric(precision=20, scale=18), nullable=True),
    sa.Column('side', sa.Integer(), server_default='1', nullable=True),
    sa.Column('status', sa.Integer(), server_default='-1', nullable=True),
    sa.Column('bk_status', sa.Integer(), server_default='-1', nullable=True),
    sa.Column('handshake_id', sa.Integer(), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['handshake_id'], ['handshake.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shaker')
    op.drop_table('handshake')
    op.drop_table('outcome')
    op.drop_table('match')
    op.drop_table('history')
    op.drop_table('event')
    op.drop_table('user')
    # ### end Alembic commands ###
