"""empty message

Revision ID: a75b97ba0b30
Revises: 961543dc2eb2
Create Date: 2018-08-08 08:01:17.641723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a75b97ba0b30'
down_revision = '961543dc2eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handshake', sa.Column('contract_address', sa.String(length=255), nullable=True))
    op.add_column('handshake', sa.Column('contract_json', sa.String(length=50), nullable=True))
    op.drop_column('handshake', 'comment_count')
    op.add_column('shaker', sa.Column('contract_address', sa.String(length=255), nullable=True))
    op.add_column('shaker', sa.Column('contract_json', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaker', 'contract_json')
    op.drop_column('shaker', 'contract_address')
    op.add_column('handshake', sa.Column('comment_count', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True))
    op.drop_column('handshake', 'contract_json')
    op.drop_column('handshake', 'contract_address')
    # ### end Alembic commands ###
