"""empty message

Revision ID: ad90b1f73795
Revises: 3abf63f34d4c
Create Date: 2018-06-01 05:19:32.184612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad90b1f73795'
down_revision = '3abf63f34d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shaker', sa.Column('bk_status', sa.Integer(), server_default='-1', nullable=True))
    op.add_column('shaker', sa.Column('status', sa.Integer(), server_default='-1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaker', 'status')
    op.drop_column('shaker', 'bk_status')
    # ### end Alembic commands ###
