"""empty message

Revision ID: b454bce515ea
Revises: 6b65288b6c69
Create Date: 2018-05-31 08:08:18.664590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b454bce515ea'
down_revision = '6b65288b6c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('homeTeamName', sa.String(length=255), nullable=True),
    sa.Column('homeTeamCode', sa.String(length=10), nullable=True),
    sa.Column('homeTeamFlag', sa.String(length=512), nullable=True),
    sa.Column('awayTeamName', sa.String(length=255), nullable=True),
    sa.Column('awayTeamCode', sa.String(length=10), nullable=True),
    sa.Column('awayTeamFlag', sa.String(length=512), nullable=True),
    sa.Column('date', sa.BigInteger(), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'device', sa.Column('deleted', sa.Integer(), nullable=True))
    op.add_column(u'handshake', sa.Column('deleted', sa.Integer(), nullable=True))
    op.add_column(u'industries', sa.Column('deleted', sa.Integer(), nullable=True))
    op.add_column(u'tx', sa.Column('deleted', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('deleted', sa.Integer(), nullable=True))
    op.add_column(u'wallet', sa.Column('deleted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'wallet', 'deleted')
    op.drop_column(u'user', 'deleted')
    op.drop_column(u'tx', 'deleted')
    op.drop_column(u'industries', 'deleted')
    op.drop_column(u'handshake', 'deleted')
    op.drop_column(u'device', 'deleted')
    op.drop_table('outcome')
    op.drop_table('match')
    # ### end Alembic commands ###
