"""empty message

Revision ID: b7e3dbd7fda8
Revises: 412e35624de9
Create Date: 2018-09-14 17:58:33.291469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7e3dbd7fda8'
down_revision = '412e35624de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handshake', 'comment_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handshake', sa.Column('comment_count', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
