"""empty message

Revision ID: b8b8179e34ea
Revises: cc7f1f8f7d7a
Create Date: 2018-06-01 12:48:16.418866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b8179e34ea'
down_revision = 'cc7f1f8f7d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handshake', sa.Column('from_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handshake', 'from_address')
    # ### end Alembic commands ###
