"""empty message

Revision ID: bddaf344e69a
Revises: 6367dd76d342
Create Date: 2018-05-31 17:21:00.088684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bddaf344e69a'
down_revision = '6367dd76d342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uid', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
