"""empty message

Revision ID: c589730163c4
Revises: 2fe51dbe7d5e
Create Date: 2018-06-06 16:06:55.180001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c589730163c4'
down_revision = '2fe51dbe7d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('name', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'name')
    # ### end Alembic commands ###
