"""empty message

Revision ID: c6c428c59f28
Revises: 140378bd9be7
Create Date: 2018-12-31 15:21:07.658080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c428c59f28'
down_revision = '140378bd9be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome', sa.Column('master_collect_status', sa.String(length=255), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome', 'master_collect_status')
    # ### end Alembic commands ###
