"""empty message

Revision ID: c82554d504aa
Revises: 694a1a355139
Create Date: 2018-11-09 11:45:28.302216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82554d504aa'
down_revision = '694a1a355139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redeem', sa.Column('is_issued', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redeem', 'is_issued')
    # ### end Alembic commands ###
