"""empty message

Revision ID: c8ff9b97b90c
Revises: f10ca3264775
Create Date: 2018-12-07 16:56:36.126789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ff9b97b90c'
down_revision = 'f10ca3264775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('comment_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'comment_count')
    # ### end Alembic commands ###
