"""empty message

Revision ID: c926a4509687
Revises: e8dea3c3ab73
Create Date: 2019-02-17 23:28:57.722594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c926a4509687'
down_revision = 'e8dea3c3ab73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onchain_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onchain_task',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('data', mysql.TEXT(), nullable=True),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text(u"'-1'"), autoincrement=False, nullable=True),
    sa.Column('modified_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('contract_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('from_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contract_method', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contract_json', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], [u'user.id'], name=u'onchain_task_ibfk_1'),
    sa.ForeignKeyConstraint(['modified_user_id'], [u'user.id'], name=u'onchain_task_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
