"""empty message

Revision ID: c9837711a468
Revises: 1ce7915a089e
Create Date: 2018-07-10 11:48:11.386137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9837711a468'
down_revision = '1ce7915a089e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('approved', sa.Integer(), server_default='-1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'approved')
    # ### end Alembic commands ###
