"""empty message

Revision ID: cc7f1f8f7d7a
Revises: ad90b1f73795
Create Date: 2018-06-01 10:09:00.116746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc7f1f8f7d7a'
down_revision = 'ad90b1f73795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    op.drop_table('wallet')
    op.drop_table('industries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('backgroundColor', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('desc', mysql.TEXT(), nullable=True),
    sa.Column('public', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('order_id', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('modified_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], [u'user.id'], name=u'industries_ibfk_1'),
    sa.ForeignKeyConstraint(['modified_user_id'], [u'user.id'], name=u'industries_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('wallet',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('private_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text(u"'1'"), autoincrement=False, nullable=True),
    sa.Column('source', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('modified_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], [u'user.id'], name=u'wallet_ibfk_1'),
    sa.ForeignKeyConstraint(['modified_user_id'], [u'user.id'], name=u'wallet_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'wallet_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('device',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('device_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('device_type', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('modified_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], [u'user.id'], name=u'device_ibfk_1'),
    sa.ForeignKeyConstraint(['modified_user_id'], [u'user.id'], name=u'device_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'device_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
