"""empty message

Revision ID: cffb90fad7e6
Revises: 715e4ace7caf
Create Date: 2018-08-16 14:53:20.819365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cffb90fad7e6'
down_revision = '715e4ace7caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('date_modified', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('to', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('data', mysql.TEXT(), nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('expire_time', mysql.DATETIME(), nullable=True),
    sa.Column('modified_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], [u'user.id'], name=u'notification_ibfk_1'),
    sa.ForeignKeyConstraint(['modified_user_id'], [u'user.id'], name=u'notification_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
