"""empty message

Revision ID: d1fc63ce0983
Revises: f65d7b059f87
Create Date: 2018-10-10 11:10:04.291044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fc63ce0983'
down_revision = 'f65d7b059f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handshake', sa.Column('from_request', sa.String(length=255), server_default='', nullable=True))
    op.add_column('outcome', sa.Column('from_request', sa.String(length=255), server_default='', nullable=True))
    op.add_column('shaker', sa.Column('from_request', sa.String(length=255), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shaker', 'from_request')
    op.drop_column('outcome', 'from_request')
    op.drop_column('handshake', 'from_request')
    # ### end Alembic commands ###
