"""empty message

Revision ID: d5a0beba6de0
Revises: 42b17acb4ab5
Create Date: 2018-05-30 00:17:42.393350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a0beba6de0'
down_revision = '42b17acb4ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handshake', sa.Column('shaked_user_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handshake', 'shaked_user_ids')
    # ### end Alembic commands ###
