"""empty message

Revision ID: d688e7d7307a
Revises: 57cf0a7f396f
Create Date: 2018-10-23 09:08:06.353368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd688e7d7307a'
down_revision = '57cf0a7f396f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redeem', sa.Column('used_user', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redeem', 'used_user')
    # ### end Alembic commands ###
