"""empty message

Revision ID: e48cc83f7171
Revises: 46eab8e53d1c
Create Date: 2018-08-09 14:32:48.762169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e48cc83f7171'
down_revision = '46eab8e53d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onchain_task', sa.Column('contract_json', sa.String(length=255), nullable=True))
    op.drop_column('onchain_task', 'contract_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onchain_task', sa.Column('contract_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('onchain_task', 'contract_json')
    # ### end Alembic commands ###
