"""empty message

Revision ID: e8dea3c3ab73
Revises: c6c428c59f28
Create Date: 2019-02-12 09:38:43.940361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8dea3c3ab73'
down_revision = 'c6c428c59f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tx', sa.Column('task_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'tx_ibfk_3', 'tx', type_='foreignkey')
    op.create_foreign_key(None, 'tx', 'task', ['task_id'], ['id'])
    op.drop_column('tx', 'onchain_task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tx', sa.Column('onchain_task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tx', type_='foreignkey')
    op.create_foreign_key(u'tx_ibfk_3', 'tx', 'onchain_task', ['onchain_task_id'], ['id'])
    op.drop_column('tx', 'task_id')
    # ### end Alembic commands ###
