"""empty message

Revision ID: ee50c9d11bb9
Revises: febba7b630a1
Create Date: 2018-07-06 10:59:58.719987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee50c9d11bb9'
down_revision = 'febba7b630a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onchain_task', sa.Column('contract_address', sa.String(length=255), nullable=True))
    op.add_column('onchain_task', sa.Column('from_address', sa.String(length=255), nullable=True))
    op.drop_column('onchain_task', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onchain_task', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('onchain_task', 'from_address')
    op.drop_column('onchain_task', 'contract_address')
    # ### end Alembic commands ###
