"""empty message

Revision ID: f0c3dfd07079
Revises: fac3dfc0f295
Create Date: 2018-11-23 16:18:37.363214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c3dfd07079'
down_revision = 'fac3dfc0f295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invited_by_user', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'invited_by_user')
    # ### end Alembic commands ###
