"""empty message

Revision ID: f10ca3264775
Revises: 86a8cf01a358
Create Date: 2018-12-07 11:52:26.346064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10ca3264775'
down_revision = '86a8cf01a358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('chain_id', sa.Integer(), server_default='4', nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('free_bet', sa.Integer(), server_default='0', nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('contract_address', sa.String(length=255), nullable=True),
    sa.Column('contract_json', sa.String(length=50), nullable=True),
    sa.Column('odds', sa.Numeric(precision=20, scale=1), nullable=True),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('from_request', sa.String(length=255), server_default='', nullable=True),
    sa.Column('side', sa.Integer(), server_default='1', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('modified_user_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'handshake', sa.Column('history_id', sa.Integer(), nullable=True))
    op.add_column(u'shaker', sa.Column('history_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'shaker', 'history_id')
    op.drop_column(u'handshake', 'history_id')
    op.drop_table('history')
    # ### end Alembic commands ###
