"""empty message

Revision ID: f65d7b059f87
Revises: e8b487e29633
Create Date: 2018-10-01 13:01:08.098259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65d7b059f87'
down_revision = 'e8b487e29633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_subscribe', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_subscribe')
    # ### end Alembic commands ###
