"""empty message

Revision ID: f922cd9d7247
Revises: 723f0bfda2d6
Create Date: 2018-11-30 15:51:07.422963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f922cd9d7247'
down_revision = '723f0bfda2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('code', table_name='redeem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('code', 'redeem', ['code'], unique=True)
    # ### end Alembic commands ###
