"""empty message

Revision ID: fdbfb00189cf
Revises: cffb90fad7e6
Create Date: 2018-08-16 16:23:13.597541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdbfb00189cf'
down_revision = 'cffb90fad7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome', 'tx')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome', sa.Column('tx', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
